apiVersion: v1
kind: Service
metadata:
  name: ngrok
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4040
    protocol: TCP
    nodePort: 30080  # You can specify any available NodePort here
  selector:
    app: ngrok