name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SHORT_PATH: /tmp/my-app

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Move repository to shorter path
      run: |
        mkdir -p $SHORT_PATH
        cp -r . $SHORT_PATH
      working-directory: $SHORT_PATH

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: $SHORT_PATH
        push: true
        tags: bhonebhone/my-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Get kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > $KUBECONFIG

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/my-app my-app=bhonebhone/my-app:${{ github.sha }}
