name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build -t my-app:latest .

    - name: Save Docker image to a file
      run: |
        docker save my-app:latest | gzip > my-app.tar.gz

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v2
      with:
        version: '1.24.0' # Adjust the Kubernetes version as needed

    - name: Configure kubectl
      run: |
        kubectl config set-cluster local --server=http://localhost:6443
        kubectl config set-context local --cluster=local
        kubectl config use-context local

    - name: Load Docker image into Kubernetes
      run: |
        kubectl create secret generic my-app-image --from-file=my-app.tar.gz
        kubectl apply -f k8s/deployment.yml

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/service.yml
        kubectl apply -f k8s/deployment.yml
