name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Create .kube directory
      run: mkdir -p ~/.kube
      shell: bash

    - name: Decode and set up kubeconfig
      env:
        KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG_CONTENT" | base64 -d > ~/.kube/config
      shell: bash

    - name: Verify kubeconfig
      run: kubectl config view
      shell: bash

    
    - name: Deploy Ngrok
      run: |
        kubectl apply -f k8s/ngrok-deployment.yaml --validate=false
        kubectl apply -f k8s/ngrok-service.yaml --validate=false
        kubectl rollout status deployment/ngrok
      shell: bash

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml --validate=false
        kubectl apply -f k8s/service.yaml --validate=false
        kubectl rollout status deployment/my-app
      shell: bash

    - name: Get Node IP
      id: get_node_ip
      run: |
        NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
        echo "NODE_IP=$NODE_IP" >> $GITHUB_ENV

    - name: Test Deployment
      run: |
        curl -sL -w "%{http_code}\\n" "http://${{ env.NODE_IP }}:30080" -o /dev/null
